// This file contains all the string resources for the application.

export const arStrings = {
  // Navigation
  navHome: 'الرئيسية',
  navTeachers: 'المعلمين',
  navCourses: 'الدورات',
  navVideos: 'فيديوهات',
  navBlog: 'المدونة',
  navAbout: 'عن JoTutor',
  navContact: 'تواصل معنا',

  // Header
  login: 'تسجيل الدخول',
  signup: 'إنشاء حساب',
  welcome: 'أهلاً',
  dashboard: 'لوحة التحكم',
  logout: 'تسجيل الخروج',
  // Fix: Added missing 'back' key.
  back: 'رجوع',

  // Language Confirmation
  langConfirmTitle: 'تغيير اللغة',
  langConfirmMessage: 'عند تغيير اللغة يمكن ان تلاحظ تغيير في المحتوى وذلك لضمان الوصول لافضل معرفة بناءاً على اللغة. هل انت متاكد من تغيير اللغة؟',
  langConfirmYes: 'نعم، غير اللغة',
  langConfirmNo: 'لا، استمر بنفس اللغة الحالية',

  // Hero Section
  heroButton: 'ابدأ رحلتك التعليمية',

  // Features Section
  featuresTitle: 'لماذا تختار JoTutor؟',
  featuresSubtitle: 'نحن نقدم تجربة تعليمية فريدة ومصممة خصيصًا لتلبية احتياجاتك.',
  feature1Title: 'معلمون خبراء',
  feature1Desc: 'نخبة من أفضل المعلمين والمعلمات لمساعدتك على التفوق الدراسي.',
  feature2Title: 'مناهج متكاملة',
  feature2Desc: 'تغطية شاملة لجميع المناهج الدراسية المحلية والدولية.',
  feature3Title: 'مرونة في المواعيد',
  feature3Desc: 'اختر الأوقات التي تناسبك لدروسك الخصوصية عبر الإنترنت.',

  // How It Works
  howItWorksTitle: 'كيف يعمل؟',
  howItWorksSubtitle: 'ابدأ رحلتك التعليمية في ثلاث خطوات بسيطة.',
  step1Title: 'ابحث عن معلم',
  step1Desc: 'تصفح قائمة المعلمين واختر الأنسب لاحتياجاتك.',
  step2Title: 'احجز حصة',
  step2Desc: 'اختر الموعد المناسب لك وقم بحجز حصتك الدراسية بسهولة.',
  step3Title: 'ابدأ التعلم',
  step3Desc: 'انضم إلى حصتك عبر الإنترنت وابدأ رحلة التفوق.',

  // Teacher Search
  teacherSearchTitle: 'ابحث عن معلمك المثالي',
  teacherSearchSubtitle: 'تواصل مع أفضل المعلمين الخصوصيين في الأردن.',
  searchByName: 'ابحث بالاسم...',
  allSubjects: 'كل المواد',
  discoverMoreTeachers: 'اكتشف المزيد من المعلمين',
  yearsExperience: 'سنوات خبرة',
  viewProfile: 'عرض الملف الشخصي',

  // Testimonials
  testimonialsTitle: 'ماذا يقولون عنا',
  testimonialsSubtitle: 'آراء طلابنا وأولياء أمورهم هي شهادتنا الأغلى.',

  // Footer
  footerDescription: 'منصة JoTutor هي بوابتك للتعليم المتميز، حيث نوفر لك أفضل المعلمين الخصوصيين لمساعدتك على تحقيق أهدافك الأكاديمية.',
  footerQuickLinks: 'روابط سريعة',
  footerLegal: 'قانوني',
  footerJoinTeacher: 'انضم كمعلم',
  footerFAQ: 'الأسئلة الشائعة',
  footerRights: 'JoTutor. جميع الحقوق محفوظة.',

  // AI Lesson Planner
  aiPlannerTitle: 'مخطط الدروس الذكي',
  aiPlannerSubtitle: 'استخدم الذكاء الاصطناعي لإنشاء خطط دروس متكاملة في ثوانٍ.',
  subject: 'المادة',
  level: 'المستوى',
  topic: 'موضوع الدرس',
  topicPlaceholder: 'مثال: مقدمة في الجبر',
  generatePlan: 'أنشئ الخطة',
  generating: 'جاري الإنشاء',
  suggestedPlan: 'الخطة المقترحة',
  errorEnterTopic: 'الرجاء إدخال موضوع الدرس.',
  errorFailedPlan: 'حدث خطأ أثناء إنشاء الخطة. الرجاء المحاولة مرة أخرى.',

  // Onboarding & Auth
  loginWelcome: 'أهلاً بعودتك!',
  email: 'البريد الإلكتروني',
  password: 'كلمة المرور',
  signupTitle: 'انضم إلى مجتمع JoTutor',
  signupDesc: 'اختر نوع الحساب الذي يناسبك.',
  signupNewStudent: 'تسجيل طالب جديد',
  signupJoinTeacher: 'الانضمام كمعلم',
  onboardingStep1Title: 'من سيستخدم الحساب؟',
  onboardingStep1Desc: 'اختر نوع المستخدم.',
  userTypeStudent: 'طالب',
  userTypeParent: 'ولي أمر',
  onboardingStep2Title: 'ما هي الخدمة التي تبحث عنها؟',
  onboardingStep2Desc: 'سيساعدنا هذا في تخصيص تجربتك.',
  serviceType1Desc: 'لتقوية المهارات الأساسية في القراءة والكتابة والرياضيات.',
  serviceType2Desc: 'للمساعدة في الواجبات المدرسية والاستعداد للامتحانات.',
  serviceType3Desc: 'للحصول على دعم إتباعي في مواد معينة.',
  serviceType4Desc: 'للاستعداد لامتحانات الشهادات الدولية والجامعية.',
  serviceType5Desc: 'لتعلم لغات جديدة أو تحسين مهاراتك اللغوية.',
  onboardingStep3Title: 'في أي مرحلة دراسية؟',
  onboardingStep3Desc: 'اختر المرحلة التعليمية الحالية.',
  educationStage1Desc: 'من رياض الأطفال إلى الصف الثالث.',
  educationStage2Desc: 'من الصف الرابع إلى الصف السادس.',
  educationStage3Desc: 'من الصف السابع إلى الصف الثاني عشر.',
  educationStage4Desc: 'التحضير للبكالوريا الدولية، SAT، IG.',
  educationStage5Desc: 'لطلاب الجامعات أو الراغبين في التعلم.',
  onboardingStep4Title: 'ما هو الصف الدراسي؟',
  onboardingStep4Desc: 'أدخل الصف الدراسي الحالي.',
  gradePlaceholder: 'مثال: الصف العاشر، سنة أولى جامعة',
  onboardingStep5Title: 'ما هو المنهاج المتبع؟',
  onboardingStep5Desc: 'اختر المنهاج الذي تدرسه.',
  onboardingStep6Title: 'ما هي المواد التي تحتاج فيها إلى مساعدة؟',
  onboardingStep6Desc: 'يمكنك اختيار أكثر من مادة.',
  onboardingStep6Title_languages: 'ما هي اللغات التي تود تعلمها؟',
  onboardingStep6Desc_languages: 'اختر اللغات التي تهمك.',
  onboardingStep7Title: 'معلوماتك الشخصية',
  onboardingStep7Desc: 'لن يستغرق الأمر سوى دقيقة.',
  fullName: 'الاسم الكامل',
  age: 'العمر',
  phone: 'رقم الهاتف',
  onboardingStep8Title: 'الخطوة الأخيرة!',
  onboardingStep8Desc: 'هل أنت مستعد لبدء رحلتك التعليمية؟',
  verificationMessage: 'سنقوم بمراجعة طلبك وسيتواصل معك أحد مستشارينا التعليميين خلال 24 ساعة.',
  agreeToTerms: 'أوافق على الشروط والأحكام وسياسة الخصوصية.',
  next: 'التالي',
  finishSignup: 'إنهاء التسجيل',
  errorGradeRequired: 'الرجاء إدخال الصف الدراسي.',
  errorSubjectsRequired: 'الرجاء اختيار مادة واحدة على الأقل.',
  errorFullNameRequired: 'الرجاء إدخال الاسم الكامل.',
  errorAgeRequired: 'الرجاء إدخال العمر.',
  errorPhoneRequired: 'الرجاء إدخال رقم الهاتف.',
  errorEmailInvalid: 'الرجاء إدخال بريد إلكتروني صحيح.',
  errorPasswordInvalid: 'يجب أن تتكون كلمة المرور من 6 أحرف على الأقل.',
  errorAgreeToTerms: 'يجب الموافقة على الشروط والأحكام.',
  errorEmailInUse: 'هذا البريد الإلكتروني مستخدم بالفعل من قبل حساب آخر.',
  errorSignupGeneric: 'حدث خطأ غير متوقع أثناء التسجيل. يرجى المحاولة مرة أخرى.',
  errorInvalidCredentials: 'البريد الإلكتروني أو كلمة المرور غير صحيحة.',

  // Dashboard
  myCourses: 'دوراتي',
  enrolledCoursesTitle: 'الدورات المسجل بها',
  noEnrolledCourses: 'أنت غير مسجل في أي دورات حاليًا.',
  suggestedCoursesTitle: 'دورات مقترحة لك',
  suggestedCoursesDesc: 'دورات مقترحة لك بناءً على اهتماماتك.',
  noSuggestedCourses: 'لا توجد دورات مقترحة حاليًا.',
  noSuggestedCoursesDesc: 'استكشف مكتبة الدورات لدينا للعثور على ما يناسبك.',
  dashboardProfile: 'الملف الشخصي',
  dashboardWallet: 'المحفظة',
  dashboardAI: 'المساعد الذكي',

  // Pages
  privacyTitle: 'سياسة الخصوصية',
  termsTitle: 'شروط الاستخدام',
  paymentRefundTitle: 'سياسة الدفع والإرجاع',
  contactTitle: 'تواصل معنا',
  contactInfo: 'معلومات التواصل',
  contactFormTitle: 'أرسل لنا رسالة',
  yourName: 'اسمك الكامل',
  yourEmail: 'بريدك الإلكتروني',
  yourMessage: 'رسالتك',
  sendMessage: 'إرسال الرسالة',
  aboutTitle: 'عن JoTutor',
  aboutVisionTitle: 'رؤيتنا',
  aboutMissionTitle: 'رسالتنا',
  aboutTeacherCommunityTitle: 'مجتمع المعلمين لدينا',
  aboutWhyJoTutorTitle: 'لماذا JoTutor؟',
  joinTeacherTitle: 'انضم إلى فريقنا من المعلمين المتميزين',
  joinTeacherDesc: 'إذا كنت معلمًا شغوفًا ولديك خبرة، فنحن نود أن نسمع منك.',
  applyNow: 'قدم الآن',
  faqTitle: 'الأسئلة الشائعة',
  blogTitle: 'مدونة JoTutor',
  by: 'تشمل المواد التالية',
  sessions: 'حصص',
  hours: 'ساعة/لكل حصة',
  readMore: 'اقرأ المزيد',
  backToBlog: 'العودة إلى المدونة',
  videosTitle: 'فيديوهات تعليمية قصيرة',
  backToVideos: 'العودة إلى الفيديوهات',

  // Courses
  coursesPreviewTitle: 'أحدث الدورات',
  coursesPreviewSubtitle: 'تصفح أحدث الدورات المضافة في مختلف المجالات.',
  discoverMoreCourses: 'اكتشف المزيد من الدورات',
  coursesTitle: 'استكشف دوراتنا',
  coursesSubtitle: 'ابحث عن الدورة المثالية التي تناسب أهدافك التعليمية.',
  category: 'الفئة',
  allCategories: 'كل الفئات',
  allLevels: 'كل المستويات',
  sortBy: 'ترتيب حسب',
  sortDefault: 'افتراضي',
  sortPriceAsc: 'السعر: من الأقل إلى الأعلى',
  sortPriceDesc: 'السعر: من الأعلى إلى الأقل',
  noCoursesFound: 'لم يتم العور على دورات.',
  noCoursesFoundDesc: 'حاول تعديل فلاتر البحث للعثور على ما تبحث عنه.',
  bookCourse: 'احجز الدورة الآن',
  courseTeacher: 'المعلم',
  courseDuration: 'المدة',
  courseLevel: 'المستوى',
  jod: 'د.أ',
  usd: '$',
  sar: 'ر.س',

  // Payment
  paymentTitle: 'إتمام عملية الدفع',
  courseSummary: 'ملخص الدورة',
  totalAmount: 'المبلغ الإجمالي',
  paymentMethod: 'طريقة الدفع',
  cardHolder: 'اسم حامل البطاقة',
  cardNumber: 'رقم البطاقة',
  expiryDate: 'تاريخ الانتهاء',
  cvv: 'CVV',
  confirmPayment: 'تأكيد الدفع',
  paymentSuccess: 'تم الدفع بنجاح!',

  // Chatbot
  chatbotTooltip: 'مرحباً! أنا Mr.Pincel. هل تحتاج إلى مساعدة؟',
  chatbotWelcome: 'أهلاً بك! أنا Mr.Pincel، مساعدك التعليمي الذكي. كيف يمكنني مساعدتك اليوم؟',
  chatbotTitle: 'Mr.Pincel - المساعد التعليمي',
  chatbotRecommendedCourses: 'دورات مقترحة لك:',
  chatbotTyping: 'Mr.Pincel يكتب...',
  chatbotPlaceholder: 'اسأل Mr.Pincel...',
  chatbotSend: 'إرسال',

  // Admin
  adminPanelTitle: 'لوحة تحكم المشرف',
  adminNavContent: 'إدارة المحتوى',
  adminNavHero: 'إدارة بنر الرئيسية',
  adminNavOnboarding: 'مراحل التسجيل',
  adminNavUsers: 'إدارة المستخدمين',
  adminNavStaff: 'إدارة الموظفين',
  adminNavPayments: 'إدارة الدفعات',
  adminNavTeachers: 'إدارة المعلمين',
  adminNavCourses: 'إدارة الدورات',
  adminNavTestimonials: 'إدارة الشهادات',
  adminNavBlog: 'إدارة المدونة',
  adminNavWhatsapp: 'الدورات عبر واتساب',
  paymentGatewayTitle: 'بوابة الدفع البنكية',
  securePaymentSystem: 'نظام دفع فعلي مشفر',
  subscriptionInvoice: 'فاتورة الاشتراك',
  amountToPay: 'المبلغ المستحق للدفع',
  bankCard: 'البطاقة البنكية',
  cliqTransfer: 'تحويل بنكي / CliQ',
  startBankConnection: 'بدء الاتصال بالبنك',
  identityVerification: 'التحقق من الهوية البنكية',
  month: 'الشهر',
  year: 'السنة',
  payAmount: 'ادفع',
  securePayment: 'دفع آمن',
  jodLabel: 'دينار',
  sessionRefreshed: '(تم تحديث الجلسة تلقائياً، يرجى إدخال البطاقة والمحاولة مجدداً)',
  // Manual Payment
  eWallets: 'المحافظ الإلكترونية',
  bankTransfer: 'التحويل البنكي',
  paymentDetailsTitle: 'معلومات الدفع',
  cliqUsername: 'اسم المستخدم',
  walletNumber: 'رقم المحفظة',
  accountName: 'اسم الحساب',
  accountNumber: 'رقم الحساب',
  importantNote: 'ملاحظة مهمة:',
  contactWhatsApp: 'التواصل عبر الواتساب',
  manualPaymentInstruction: 'في حال الدفع بأي من الطرق السابقة، يرجى إرسال الفاتورة/إيصال الدفع إلى رقمنا عبر الواتساب لتأكيد الدفع وتفعيل الدورة.',
  close: 'إغلاق',
  confirmManualTransfer: 'تأكيد إرسال الحوالة',
  etihadBank: 'بنك الاتحاد',
  arabBank: 'البنك العربي',
  iban: 'الآيبان (IBAN)',
};

export const enStrings = {
  navHome: 'Home',
  navTeachers: 'Teachers',
  navCourses: 'Courses',
  navVideos: 'Videos',
  navBlog: 'Blog',
  navAbout: 'About Us',
  navContact: 'Contact Us',
  login: 'Login',
  signup: 'Sign Up',
  welcome: 'Welcome',
  dashboard: 'Dashboard',
  logout: 'Logout',
  back: 'Back',
  langConfirmTitle: 'Change Language',
  langConfirmMessage: 'When changing the language, you may notice a change in content to ensure access to the best knowledge based on the language. Are you sure you want to change the language?',
  langConfirmYes: 'Yes, change language',
  langConfirmNo: 'No, keep current language',
  heroButton: 'Start Your Learning Journey',
  featuresTitle: 'Why Choose JoTutor?',
  featuresSubtitle: 'We offer a unique learning experience tailored to your needs.',
  feature1Title: 'Expert Tutors',
  feature1Desc: 'A selection of the best teachers to help you excel academically.',
  feature2Title: 'Integrated Curricula',
  feature2Desc: 'Comprehensive coverage of all local and international curricula.',
  feature3Title: 'Flexible Scheduling',
  feature3Desc: 'Choose the times that suit you for your online private lessons.',
  howItWorksTitle: 'How It Works',
  howItWorksSubtitle: 'Start your educational journey in three simple steps.',
  step1Title: 'Find a Tutor',
  step1Desc: 'Browse our list of tutors and choose the best one for your needs.',
  step2Title: 'Book a Session',
  step2Desc: 'Select a suitable time and easily book your study session.',
  step3Title: 'Start Learning',
  step3Desc: 'Join your online session and begin your journey to excellence.',
  teacherSearchTitle: 'Find Your Perfect Tutor',
  teacherSearchSubtitle: 'Connect with the best private tutors in Jordan.',
  searchByName: 'Search by name...',
  allSubjects: 'All Subjects',
  discoverMoreTeachers: 'Discover More Teachers',
  yearsExperience: 'years of experience',
  viewProfile: 'View Profile',
  testimonialsTitle: 'What They Say About Us',
  testimonialsSubtitle: 'The opinions of our students and their parents are our most valuable testimony.',
  footerDescription: 'JoTutor is your gateway to excellent education, providing you with the best private tutors to help you achieve your academic goals.',
  footerQuickLinks: 'Quick Links',
  footerLegal: 'Legal',
  footerJoinTeacher: 'Join as a Teacher',
  footerFAQ: 'FAQ',
  footerRights: 'JoTutor. All rights reserved.',
  aiPlannerTitle: 'AI Lesson Planner',
  aiPlannerSubtitle: 'Use AI to create comprehensive lesson plans in seconds.',
  subject: 'Subject',
  level: 'Level',
  topic: 'Lesson Topic',
  topicPlaceholder: 'e.g., Introduction to Algebra',
  generatePlan: 'Generate Plan',
  generating: 'Generating',
  suggestedPlan: 'Suggested Plan',
  errorEnterTopic: 'Please enter a lesson topic.',
  errorFailedPlan: 'Failed to generate plan. Please try again.',
  loginWelcome: 'Welcome Back!',
  email: 'Email',
  password: 'Password',
  signupTitle: 'Join the JoTutor Community',
  signupDesc: 'Choose the account type that suits you.',
  signupNewStudent: 'Register as a New Student',
  signupJoinTeacher: 'Join as a Teacher',
  onboardingStep1Title: "Who will be using the account?",
  onboardingStep1Desc: "Select the user type.",
  userTypeStudent: "Student",
  userTypeParent: "Parent",
  onboardingStep2Title: "What service are you looking for?",
  onboardingStep2Desc: "This will help us personalize your experience.",
  serviceType1Desc: "To strengthen basic skills in reading, writing, and math.",
  serviceType2Desc: "For help with homework and exam preparation.",
  serviceType3Desc: "To get extra support in specific subjects.",
  serviceType4Desc: "To prepare for international and university entrance exams.",
  serviceType5Desc: "To learn new languages or improve your language skills.",
  onboardingStep3Title: "What is the academic stage?",
  onboardingStep3Desc: "Choose the current educational stage.",
  educationStage1Desc: "From kindergarten to 3rd grade.",
  educationStage2Desc: "From 4th to 6th grade.",
  educationStage3Desc: "From 7th to 12th grade.",
  educationStage4Desc: "Preparation for IB, SAT, IG.",
  educationStage5Desc: "For university students or lifelong learners.",
  onboardingStep4Title: "What is the grade level?",
  onboardingStep4Desc: "Enter the current grade level.",
  gradePlaceholder: "e.g., 10th Grade, 1st Year University",
  onboardingStep5Title: "What curriculum are you following?",
  onboardingStep5Desc: "Choose the curriculum you are studying.",
  onboardingStep6Title: "Which subjects do you need help with?",
  onboardingStep6Desc: "You can choose more than one subject.",
  onboardingStep6Title_languages: "What languages would you like to learn?",
  onboardingStep6Desc_languages: "Choose the languages that interest you.",
  onboardingStep7Title: "Your Personal Information",
  onboardingStep7Desc: "It will only take a minute.",
  fullName: "Full Name",
  age: "Age",
  phone: "Phone Number",
  onboardingStep8Title: "Final Step!",
  onboardingStep8Desc: "Are you ready to start your learning journey?",
  verificationMessage: "We will review your application and one of our educational consultants will contact you within 24 hours.",
  agreeToTerms: "I agree to the Terms & Conditions and Privacy Policy.",
  next: "Next",
  finishSignup: "Finish Signup",
  errorGradeRequired: "Please enter your grade.",
  errorSubjectsRequired: "Please select at least one subject.",
  errorFullNameRequired: "Please enter your full name.",
  errorAgeRequired: "Please enter your age.",
  errorPhoneRequired: "Please enter your phone number.",
  errorEmailInvalid: "Please enter a valid email.",
  errorPasswordInvalid: "Password must be at least 6 characters.",
  errorAgreeToTerms: "You must agree to the terms and conditions.",
  errorEmailInUse: 'This email address is already in use by another account.',
  errorSignupGeneric: 'An unexpected error occurred during signup. Please try again.',
  errorInvalidCredentials: 'Invalid email or password.',
  myCourses: 'My Courses',
  enrolledCoursesTitle: 'Enrolled Courses',
  noEnrolledCourses: "You are not currently enrolled in any courses.",
  suggestedCoursesTitle: 'Suggested Courses',
  suggestedCoursesDesc: 'Courses suggested for you based on your interests.',
  noSuggestedCourses: 'No suggested courses at the moment.',
  noSuggestedCoursesDesc: 'Explore our course library to find what suits you.',
  dashboardProfile: 'Profile',
  dashboardWallet: 'Wallet',
  dashboardAI: 'AI Assistant',
  privacyTitle: 'Privacy Policy',
  termsTitle: 'Terms of Service',
  paymentRefundTitle: 'Payment & Refund Policy',
  contactTitle: 'Contact Us',
  contactInfo: 'Contact Information',
  contactFormTitle: 'Send Us a Message',
  yourName: 'Your Name',
  yourEmail: 'Your Email',
  yourMessage: 'Your Message',
  sendMessage: 'Send Message',
  aboutTitle: 'About JoTutor',
  aboutVisionTitle: 'Our Vision',
  aboutMissionTitle: 'Our Mission',
  aboutTeacherCommunityTitle: 'Our Teacher Community',
  aboutWhyJoTutorTitle: 'Why JoTutor?',
  joinTeacherTitle: 'Join Our Team of Excellent Teachers',
  joinTeacherDesc: 'If you are a passionate and experienced teacher, we would love to hear from you.',
  applyNow: 'Apply Now',
  faqTitle: 'Frequently Asked Questions',
  blogTitle: 'JoTutor Blog',
  by: 'By',
  // Fix: Added missing keys for sync.
  sessions: 'Sessions',
  hours: 'Hrs/Session',
  readMore: 'Read More',
  backToBlog: 'Back to Blog',
  videosTitle: 'Short Educational Videos',
  backToVideos: 'Back to Videos',
  coursesPreviewTitle: 'Latest Courses',
  coursesPreviewSubtitle: 'Browse the latest courses added in various fields.',
  discoverMoreCourses: 'Discover More Courses',
  coursesTitle: 'Explore Our Courses',
  coursesSubtitle: 'Find the perfect course that fits your educational goals.',
  category: 'Category',
  allCategories: 'All Categories',
  allLevels: 'All Levels',
  sortBy: 'Sort By',
  sortDefault: 'Default',
  sortPriceAsc: 'Price: Low to High',
  sortPriceDesc: 'Price: High to Low',
  noCoursesFound: 'No courses found.',
  noCoursesFoundDesc: 'Try adjusting your search filters to find what you are looking for.',
  bookCourse: 'Book Course Now',
  courseTeacher: 'Teacher',
  courseDuration: 'Duration',
  courseLevel: 'Level',
  jod: 'JOD',
  usd: 'USD',
  sar: 'SAR',
  paymentTitle: 'Complete Your Payment',
  courseSummary: 'Course Summary',
  totalAmount: 'Total Amount',
  paymentMethod: 'Payment Method',
  cardHolder: 'Cardholder Name',
  cardNumber: 'Card Number',
  expiryDate: 'Expiry Date',
  cvv: 'CVV',
  confirmPayment: 'Confirm Payment',
  paymentSuccess: 'Payment successful!',
  chatbotTooltip: "Hi! Need help finding a course? I'm here to assist!",
  chatbotWelcome: 'Welcome to the JoTutor Assistant! How can I help you find the perfect course today?',
  chatbotTitle: 'JoTutor Assistant',
  chatbotRecommendedCourses: 'Recommended courses for you:',
  chatbotTyping: 'Typing...',
  chatbotPlaceholder: 'Ask about a course...',
  chatbotSend: 'Send',
  adminPanelTitle: 'Admin Control Panel',
  adminNavContent: 'Content Management',
  adminNavHero: 'Home Banner',
  adminNavOnboarding: 'Onboarding Steps',
  adminNavUsers: 'User Management',
  adminNavStaff: 'Staff Management',
  adminNavPayments: 'Payments',
  adminNavTeachers: 'Teacher Management',
  adminNavCourses: 'Course Management',
  adminNavTestimonials: 'Testimonials',
  adminNavBlog: 'Blog Management',
  adminNavWhatsapp: 'WhatsApp Courses',
  paymentGatewayTitle: 'Banking Payment Gateway',
  securePaymentSystem: 'Encrypted Live Payment System',
  subscriptionInvoice: 'Subscription Invoice',
  amountToPay: 'Amount to Pay',
  bankCard: 'Bank Card',
  cliqTransfer: 'Bank / CliQ Transfer',
  startBankConnection: 'Start Bank Connection',
  identityVerification: 'Bank Identity Verification',
  month: 'Month',
  year: 'Year',
  payAmount: 'Pay',
  securePayment: 'Secure Payment',
  jodLabel: 'JOD',
  sessionRefreshed: '(Session refreshed automatically, please enter card details and try again)',
  // Manual Payment
  eWallets: 'E-Wallets',
  bankTransfer: 'Bank Transfer',
  paymentDetailsTitle: 'Payment Information',
  cliqUsername: 'Username',
  walletNumber: 'Wallet Number',
  accountName: 'Account Name',
  accountNumber: 'Account Number',
  importantNote: 'Important Note:',
  contactWhatsApp: 'Contact via WhatsApp',
  manualPaymentInstruction: 'In case of payment by any of the above methods, please send the invoice/payment receipt to our number via WhatsApp to confirm the payment and activate the course.',
  close: 'Close',
  confirmManualTransfer: 'Confirm Transfer Sent',
  etihadBank: 'Etihad Bank',
  arabBank: 'Arab Bank',
  iban: 'IBAN',
};